"""added basic User Auth

Revision ID: 10b6c752f04e
Revises: 57a34ba57456
Create Date: 2026-01-02 18:31:22.770130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b6c752f04e'
down_revision: Union[str, Sequence[str], None] = '57a34ba57456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_completions', schema=None) as batch_op:
        batch_op.alter_column('period_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_completions', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('period_key',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
