"""introduction of duedate and more date remodelling to iso date format

Revision ID: 57a34ba57456
Revises: c089bc13427c
Create Date: 2025-12-31 14:06:03.022302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a34ba57456'
down_revision: Union[str, Sequence[str], None] = 'c089bc13427c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
        batch_op.add_column(
            sa.Column("due_date", sa.Date(), nullable=True)
        )
        batch_op.alter_column('created_at',
                existing_type=sa.TEXT(),
                type_=sa.Date(),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_completions', 'completed_at',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('todo_completions', 'period_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
