"""changed to date vars instead of str for date columns

Revision ID: 92645ea71009
Revises: d8a9a40f8cc3
Create Date: 2025-12-31 12:16:41.114283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92645ea71009'
down_revision: Union[str, Sequence[str], None] = 'd8a9a40f8cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
        batch_op.alter_column(
            "start_date",
            existing_type=sa.TEXT(),
            type_=sa.Date(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "completed_at",
            existing_type=sa.TEXT(),
            type_=sa.Date(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed_at',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('todos', 'start_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
