"""introduction of duedate and more date remodelling to iso date format

Revision ID: a556d850286e
Revises: 92645ea71009
Create Date: 2025-12-31 13:50:58.164053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a556d850286e"
down_revision: Union[str, Sequence[str], None] = "92645ea71009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
        batch_op.add_column(sa.Column("due_date", sa.Date(), nullable=True))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TEXT(),
            type_=sa.Date(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "todos",
        "created_at",
        existing_type=sa.Date(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("todos", "due_date")
    # ### end Alembic commands ###
