"""init

Revision ID: d8a9a40f8cc3
Revises: 
Create Date: 2025-12-29 12:08:07.581362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a9a40f8cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('recurrence_type', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_id', 'period_key', name='uq_todo_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_completions')
    op.drop_table('todos')
    # ### end Alembic commands ###
